@startuml compania de seguros
'https://plantuml.com/class-diagram

left to right direction
skinparam classAttributeIconSize 0

class Compañia{
-idCentrales : numeric
}

class Edificios{
-idEdificios : numeric
-idCentrales : numeric
-tiposDeAlarma : numeric
}
class TiposDeAlarma{
+AlarmaFuego
+AlarmaRobo
}
class AlarmaFuego{
llamarPolicia()
llamarBomberos()
}
class AlarmaRobo{
llamarPolicia()
}

Compañia "1" --> "1..*" Edificios : instalada alarma
Edificios "1..n" --> "0..2" TiposDeAlarma : instalado


@enduml