@startuml

'Especificar un diagrama de clases que describa los vuelos que oferta una compañía de viajes según
 'la siguiente especificación:
 '• La compañía oferta una serie de vuelos para unas fechas concretas y con un número de
 'plazas.
 '• La compañía dispone de una flota de aviones con una capacidad que da soporte a los vuelos
 'ofertados.
 '• Las personas compran billetes para los vuelos que le interesan. Para emitir el billete es
 'necesario conocer el nombre, apellidos y edad del pasajero.
 '• Los billetes identifican el número de asiento que ocupan

class Vuelo {
-plazas : Integer
-fecha : Date
}
class Avion {
-modelo : String
-capacidad : Integer
}
class Pasajero {
-nombre : String
-apellidos : String
-fechaNacimiento : Date
}
class Billete {
-asiento : Integer
}
class Oferta {
}

Vuelo -- Avion
Avion -- Billete
Billete -- Pasajero


@enduml