@startuml tienda
'https://plantuml.com/es/use-case-diagram

left to right direction
skinparam classAttributeIconSize 0

actor Comerciante

rectangle Gestion_de_inventario {

Comerciante -- (Archivo_Proveedores)
    (Archivo_Proveedores) .. (agregar proveedor) : <<include>>
    (Archivo_Proveedores) .. (lista articulos proveedor) : <<extend>>
Comerciante -- (Gestion_inventario)
    (Gestion_inventario) --> (imprimir)
    (Gestion_inventario) --> (articulos)
        (articulos) .. (agregar articulo): <<extend>>
        (articulos) .. (eliminar): <<extend>>
        (articulos) .. (editar): <<extend>>

(agregar articulo) ..> (agregar proveedor) : <<extend>>

}

@enduml