@startuml viajes
'https://plantuml.com/class-diagram

left to right direction
skinparam classAttributeIconSize 0

class Vuelo {
-plazas : Integer
-fecha : Date
}
class Avion {
-modelo : String
-capacidad : Integer
}
class Pasajero {
-nombre : String
-apellidos : String
-fechaNacimiento : Date
}
class Billete {
-asiento : Integer
}
class Oferta {
}

Vuelo -- Avion
Avion -- Billete
Billete -- Pasajero


@enduml