@startuml gestion de proyectos
'https://plantuml.com/class-diagram
'La  única  persona  que  controla  los  proyectos  es  el  administrador  de  proyectos,
'cuyas  funciones son las siguientes: •Puede  agregar,  eliminar  y  actualizar  un  proyecto,
'pero  para  eliminar  y  actualizar  es  necesario encontrar el proyecto en cuestión.
'   •A la hora de actualizar un proyecto se pueden dar dos situaciones:
'       ◦Cambiar la información sobre las tareas del proyecto.
'       ◦Cambiar los recursos asociados al proyecto.
'   •Para  informar  a  todos  los  miembros  del  equipo  sobre  los  avances  en
'       el  proyecto  seprocede emitiendo un documento,
'   que se envía vía e-mail o que se publica en un sitio webconocido por todos.

left to right direction
skinparam packageStyle rectangle

actor Administrador

rectangle  Lista_de_proyectos {
Administrador -- (Agregar)
Administrador -- (Buscar)
    (Buscar) --> (Eliminar)
    (Buscar) --> (Actualizar)
        (Actualizar) --> (Cambiar información)
        (Actualizar) --> (Cambio de recursos)
    (Cambiar información) --> (Informar)
    (Cambio de recursos) --> (Informar)
    (Informar) --> (Crear documento)
        (Crear documento).up.> (enviar email) : <<include>>
        (Crear documento).up.> (subir a la web) : <<include>>
}

@enduml